export const templateOptions = [
  'None',
  'ROC Compliance Service',
  'Annual Compliance plus Bookkeeping',
  'Package plus payment details',
  'ROC plus GST plus ESI plus TDS',
  'INC 20A Reminder',
  'Next Quarter Payment',
  'Service List',
  'GST Filing',
  'MSME Certification',
  'GST Registration',
  'Bookkeeping Service',
  'TDS Return Service',
  'Professional Tax Service',
  'Director Resignation',
  'Startup India Registration',
  'Startup India Promotion',
  'Website',
]

// Note: Complete Template options are identical based on the prompt
export const completeTemplateOptions = [
  'None',
  'ROC Compliance Service',
  'Annual Compliance plus Bookkeeping',
  'Package plus payment details',
  'ROC plus GST plus ESI plus TDS',
  'INC 20A Reminder',
  'Next Quarter Payment',
  'Service List',
  'GST Filing',
  'MSME Certification',
  'GST Registration',
  'Bookkeeping Service',
  'TDS Return Service',
  'Professional Tax Service',
  'Director Resignation',
  'Startup India Registration',
  'Startup India Promotion',
  'Website',
]

// For edit form "Complete Template" when expiry toggled ON in Edit
export const editCompleteTemplateOptions = [
  'ROC Compliance Service',
  'Annual Compliance plus Bookkeeping',
  'Package plus payment details',
  'ROC plus GST plus ESI plus TDS',
  'INC 20A Reminder',
  'Next Quarter Payment',
  'Service List',
  'GST Filing',
  'MSME Certification',
  'GST Registration',
  'Bookkeeping Service',
  'TDS Return Service',
  'Professional Tax Service',
  'Director Resignation',
  'Startup India Registration',
  'Startup India Promotion',
  'Website',
]

export const DUMMY_COMPLIANCES = [
  {
    id: '1',
    complianceName: 'Preparation & Filing of Form ADT-01 (Auditor Appointment)',
    hasExpiry: true,
    expiryDate: null,
    inc20: 'No',
    daysOfExpiryAfterIncData: '',
    expiryAfter: '30 days',
    new: null,
    expiryTemplate: 'Compliance Update',
    completeTemplate: 'None',
  },
  {
    id: '2',
    complianceName: 'Preparation & Filing of Form INC - 20A',
    hasExpiry: true,
    expiryDate: null,
    inc20: 'No',
    daysOfExpiryAfterIncData: '',
    expiryAfter: '180 days',
    new: null,
    expiryTemplate: 'Compliance Update',
    completeTemplate: 'None',
  },
  {
    id: '3',
    complianceName: 'Preparation of 07 Required Statutory Registers',
    hasExpiry: false,
    expiryDate: null,
    inc20: 'No',
    daysOfExpiryAfterIncData: '',
    expiryAfter: null,
    new: null,
    expiryTemplate: 'None',
    completeTemplate: 'None',
  },
  {
    id: '4',
    complianceName: 'Preparation & Filing of Form DPT - 03',
    hasExpiry: false,
    expiryDate: null,
    inc20: 'No',
    daysOfExpiryAfterIncData: '',
    expiryAfter: null,
    new: null,
    expiryTemplate: 'None',
    completeTemplate: 'None',
  },
  {
    id: '5',
    complianceName: 'Issuance of Share Certificates (for all Shareholders)',
    hasExpiry: true,
    expiryDate: null,
    inc20: 'No',
    daysOfExpiryAfterIncData: '',
    expiryAfter: '30 days',
    new: null,
    expiryTemplate: 'Compliance Update',
    completeTemplate: 'None',
  },
  {
    id: '6',
    complianceName: 'Preparation of MPB-01 (Disclosure of Interest by Directors)',
    hasExpiry: true,
    expiryDate: '2026-04-30', // 30th Apr 2026
    inc20: 'No',
    daysOfExpiryAfterIncData: '',
    expiryAfter: null,
    new: null,
    expiryTemplate: 'None',
    completeTemplate: 'None',
  },
  {
    id: '7',
    complianceName: 'Preparation of DIR-08 (Disclosure of Non-Disqualification by Directors)',
    hasExpiry: true,
    expiryDate: '2026-04-30', // 30th Apr 2026
    inc20: 'No',
    daysOfExpiryAfterIncData: '',
    expiryAfter: null,
    new: null,
    expiryTemplate: 'None',
    completeTemplate: 'None',
  },
  {
    id: '8',
    complianceName: 'Preparation & Filing of Balance Sheet and P&L Accounts',
    hasExpiry: true,
    expiryDate: '2026-09-30', // 30th Sep 2026
    inc20: 'No',
    daysOfExpiryAfterIncData: '',
    expiryAfter: null,
    new: null,
    expiryTemplate: 'Compliance Update',
    completeTemplate: 'None',
  },
  {
    id: '9',
    complianceName: 'Preparation & Filing of Audit Report, Director\'s Report & Extract of Annual Returns',
    hasExpiry: true,
    expiryDate: '2026-09-30', // 30th Sep 2026
    inc20: 'No',
    daysOfExpiryAfterIncData: '',
    expiryAfter: null,
    new: null,
    expiryTemplate: 'Compliance Update',
    completeTemplate: 'None',
  },
]
